// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAck-UrvA5GwkKa9c-u3q7YVXu_5hBuH-U',
    appId: '1:934277916463:web:26d3fd06c73485f3c7a3da',
    messagingSenderId: '934277916463',
    projectId: 'api-tato',
    authDomain: 'api-tato.firebaseapp.com',
    storageBucket: 'api-tato.firebasestorage.app',
    measurementId: 'G-0ZTD6Q0RV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjh6gwZ38VwbZ4fKSMcRMScITZVdfliB4',
    appId: '1:934277916463:android:afafedcffb8346eac7a3da',
    messagingSenderId: '934277916463',
    projectId: 'api-tato',
    storageBucket: 'api-tato.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-It9WABhvdE_YzzxHUenaiBzEIf1rIM',
    appId: '1:934277916463:ios:d786311c81d70a85c7a3da',
    messagingSenderId: '934277916463',
    projectId: 'api-tato',
    storageBucket: 'api-tato.firebasestorage.app',
    iosClientId: '934277916463-l63cq3hdl5npkbfqaijmu21gehnj1rbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appNameV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-It9WABhvdE_YzzxHUenaiBzEIf1rIM',
    appId: '1:934277916463:ios:d786311c81d70a85c7a3da',
    messagingSenderId: '934277916463',
    projectId: 'api-tato',
    storageBucket: 'api-tato.firebasestorage.app',
    iosClientId: '934277916463-l63cq3hdl5npkbfqaijmu21gehnj1rbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appNameV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAck-UrvA5GwkKa9c-u3q7YVXu_5hBuH-U',
    appId: '1:934277916463:web:1c4c76d118a5344cc7a3da',
    messagingSenderId: '934277916463',
    projectId: 'api-tato',
    authDomain: 'api-tato.firebaseapp.com',
    storageBucket: 'api-tato.firebasestorage.app',
    measurementId: 'G-8CHK5T6LMS',
  );
}
